"""fix nullable columns

Revision ID: e20cb6415067
Revises: 001
Create Date: 2026-03-21 21:33:04.771620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e20cb6415067'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment_votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'upvote_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('division_access_requests', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('division_access_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('division_access_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('forks', 'forked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('installs', 'installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('replies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'helpful_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'unhelpful_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skill_versions', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'author_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('skills', 'current_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('skills', 'install_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('skills', 'data_sensitivity',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('skills', 'external_calls',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('skills', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('skills', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('skills', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('skills', 'install_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skills', 'fork_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skills', 'favorite_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skills', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skills', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skills', 'avg_rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False)
    op.alter_column('skills', 'trending_score',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('submission_gate_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_platform_team',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_security_team',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_security_team',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_platform_team',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('submission_gate_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'trending_score',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('skills', 'avg_rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True)
    op.alter_column('skills', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skills', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skills', 'favorite_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skills', 'fork_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skills', 'install_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skills', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('skills', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('skills', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('skills', 'external_calls',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('skills', 'data_sensitivity',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('skills', 'install_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('skills', 'current_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('skills', 'author_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('skill_versions', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'unhelpful_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'helpful_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('replies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('installs', 'installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('forks', 'forked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('division_access_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('division_access_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('division_access_requests', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'upvote_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment_votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
